name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Docker image
      env:
        IMAGE_NAME:"docker.pkg.github.com /$(echo $GITHUB_REPOSITORY |  tr '[:upper:]' '[:lower:]' ):$(date +%s)"
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME
        docker login -u $(dirname $GITHUB_REPOSITORY) -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push $IMAGE_NAME
