name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Docker image
      run: |
        LOWER_REPO=$(echo $GITHUB_REPOSITORY |  tr '[:upper:]' '[:lower:]' )
        IMAGE_NAME="docker.pkg.github.com/$LOWER_REPO/$(basename $LOWER_REPO):${GITHUB_SHA::8}"
        echo "Building docker image '$IMAGE_NAME'"
        docker build . --file Dockerfile --tag $IMAGE_NAME --label "github-commit:$GITHUB_SHA" --label "github-repo:$GITHUB_REPOSITORY"
        echo ${{ secrets.GITHUB_TOKEN }} | docker login --username $(dirname $GITHUB_REPOSITORY) --password-stdin docker.pkg.github.com
        echo "Pushing docker image '$IMAGE_NAME'"
        docker push $IMAGE_NAME
