name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Docker image
      run: |
        LOWER_REPO=$(echo $GITHUB_REPOSITORY |  tr '[:upper:]' '[:lower:]' )
        IMAGE_NAME="docker.pkg.github.com/$LOWER_REPO:$(date +%s)"
        docker build . --file Dockerfile --tag $IMAGE_NAME
        docker login -u $(dirname $GITHUB_REPOSITORY) -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        echo "Pushing docker image $IMAGE_NAME"
        docker push $IMAGE_NAME
